#!/bin/bash

# jobname
#SBATCH --job-name=batch-fastref

# queue
#SBATCH --partition=amdcpu
#SBATCH --ntasks=1

# array
# change this to the number of array elements you actually need
#SBATCH --array=0-5

source ./env
python run-fast-alt.py
