#!/bin/bash

# specify resources

# max wallclock time
#SBATCH --time=2:00:00

# jobname
#SBATCH --job-name=equil

# queue
# While the Makefile doesn't set it explicitly, gromacs mdrun is gpu accelerated by default
#SBATCH --partition=a5a
#SBATCH --gpus=1

# array
#SBATCH --array=0-2
TAGS=("1EXM" "1NEP" "1JWP")

export tag="${TAGS[$SLURM_ARRAY_TASK_ID]}"

set -euxo pipefail

source ../env

make
