#!/bin/bash

# specify resources

# max wallclock time
#SBATCH --time=2:00:00

# jobname
#SBATCH --job-name=equil

# queue
#SBATCH --partition=a5000
#SBATCH --gpus=1

# array
#SBATCH --array=0-2
TAGS=("1EXM" "1NEP" "1JWP")

export tag="${TAGS[$SLURM_ARRAY_TASK_ID]}"

set -euxo pipefail
source ../GMXRC
echo $GMXBIN

make
